# Generated by Django 5.1.6 on 2025-06-19 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="服务器名称"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="服务器区域"
                    ),
                ),
            ],
            options={
                "verbose_name": "服务器",
                "verbose_name_plural": "服务器",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="昵称"
                    ),
                ),
                (
                    "game_id",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="游戏ID"
                    ),
                ),
                ("description", models.TextField(verbose_name="神人事迹")),
                (
                    "evidence",
                    models.TextField(
                        blank=True,
                        help_text="可以是图片链接或描述",
                        verbose_name="证据",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已发布"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="查看次数"),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_partners",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交者",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partners",
                        to="sfpr.server",
                        verbose_name="服务器",
                    ),
                ),
            ],
            options={
                "verbose_name": "神人记录",
                "verbose_name_plural": "神人记录",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["nickname", "game_id"],
                        name="sfpr_partne_nicknam_538533_idx",
                    ),
                    models.Index(
                        fields=["status"], name="sfpr_partne_status_740978_idx"
                    ),
                ],
            },
        ),
    ]
