# Generated by Django 5.1.6 on 2025-06-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sfpr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="server",
            field=models.IntegerField(verbose_name="服务器ID"),
        ),
        migrations.AddField(
            model_name="partner",
            name="server_name",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="服务器名称"
            ),
        ),
        migrations.DeleteModel(
            name="Server",
        ),
    ]
