# Generated by Django 5.1.6 on 2025-06-19 21:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sfpr", "0003_alter_partner_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="昵称"
                    ),
                ),
                (
                    "game_id",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="游戏ID"
                    ),
                ),
                ("server", models.IntegerField(verbose_name="服务器ID")),
                (
                    "server_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="服务器名称"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="查看次数"),
                ),
            ],
            options={
                "verbose_name": "玩家",
                "verbose_name_plural": "玩家",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["nickname", "game_id"],
                        name="sfpr_player_nicknam_ac121c_idx",
                    )
                ],
                "unique_together": {("nickname", "game_id", "server")},
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(verbose_name="神人事迹")),
                (
                    "evidence",
                    models.TextField(
                        blank=True,
                        help_text="可以是图片链接或描述",
                        verbose_name="证据",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已发布"),
                            ("rejected", "已拒绝"),
                        ],
                        default="approved",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="sfpr.player",
                        verbose_name="玩家",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交者",
                    ),
                ),
            ],
            options={
                "verbose_name": "神人事迹",
                "verbose_name_plural": "神人事迹",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Partner",
        ),
    ]
