# Generated by Django 5.1.6 on 2025-06-19 23:11

import apps.sfpr.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sfpr", "0004_player_record_delete_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="image_1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.sfpr.models.record_image_path,
                verbose_name="图片1",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="image_2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.sfpr.models.record_image_path,
                verbose_name="图片2",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="image_3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.sfpr.models.record_image_path,
                verbose_name="图片3",
            ),
        ),
    ]
